"""Initial migration img

Revision ID: 94921ef2d9a0
Revises: 
Create Date: 2023-02-23 02:53:34.764776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94921ef2d9a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_student_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_student_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_student_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_student_email'), type_='unique')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
